name: Deploy Self Discovered Project to cPanel

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.15.0'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build Angular project
        run: npm run build --prod
        
      - name: List files in dist directory for debugging
        run: ls -la dist/selfdiscovered
        
      - name: Move files from browser to selfdiscovered
        run: node movefiles.js
        if: success()
        
      - name: Debug FTP server directories
        run: |
          ftp -inv ${{ secrets.FTP_SERVER }} <<EOF
          user ${{ secrets.FTP_USERNAME }} ${{ secrets.FTP_PASSWORD }}
          ls /
          ls /public_html
          bye
          EOF
          
      - name: Deploy via FTP and check/move files in public_html
        run: |
          # Deploy via FTP
          ftp -inv ${{ secrets.FTP_SERVER }} <<EOF
          user ${{ secrets.FTP_USERNAME }} ${{ secrets.FTP_PASSWORD }}
          cd public_html
          put -r dist/selfdiscovered/*
          bye
          EOF
          
          # Check and move files in public_html
          ftp -inv ${{ secrets.FTP_SERVER }} <<EOF
          user ${{ secrets.FTP_USERNAME }} ${{ secrets.FTP_PASSWORD }}
          cd public_html
          ls
          if [ -d "public_html" ]; then
            echo "Found nested public_html directory. Moving contents one level up..."
            # Move contents (excluding 'browser' directory if exists) to parent directory
            find . -mindepth 1 -maxdepth 1 -not -name 'browser' -exec mv {} .. \;
          fi
          bye
          EOF
